### ISSUE TITLE
Serialization doesn't support LocalDateTime from Java 8 (java.time)

### ISSUE THREAD

**Issue by cooniur** [debop/hibernate-redis#37]
Here is the stack trace:

	2015-07-06 17:46:32.734  WARN 64242 --- [io-12345-exec-2] o.h.c.r.serializer.FstRedisSerializer    : Fail to deserialize bytes.

	java.io.IOException: java.lang.RuntimeException: java.io.StreamCorruptedException: Unknown serialized type
		at de.ruedigermoeller.serialization.FSTObjectInput.readObject(FSTObjectInput.java:168)
		at org.hibernate.cache.redis.serializer.FstRedisSerializer.deserialize(FstRedisSerializer.java:60)
		at org.hibernate.cache.redis.serializer.SnappyRedisSerializer.deserialize(SnappyRedisSerializer.java:41)
		at org.hibernate.cache.redis.jedis.JedisClient.deserializeValue(JedisClient.java:502)
		at org.hibernate.cache.redis.jedis.JedisClient.get(JedisClient.java:179)
		at org.hibernate.cache.redis.regions.RedisTransactionalDataRegion.get(RedisTransactionalDataRegion.java:75)
		at org.hibernate.cache.redis.strategy.TransactionalRedisEntityRegionAccessStrategy.get(TransactionalRedisEntityRegionAccessStrategy.java:55)
		at org.hibernate.engine.internal.CacheHelper.fromSharedCache(CacheHelper.java:55)
		at org.hibernate.engine.internal.CacheHelper.fromSharedCache(CacheHelper.java:67)
		at org.hibernate.event.internal.DefaultLoadEventListener.loadFromSecondLevelCache(DefaultLoadEventListener.java:597)
		at org.hibernate.event.internal.DefaultLoadEventListener.doLoad(DefaultLoadEventListener.java:451)
		at org.hibernate.event.internal.DefaultLoadEventListener.load(DefaultLoadEventListener.java:212)
		at org.hibernate.event.internal.DefaultLoadEventListener.proxyOrLoad(DefaultLoadEventListener.java:274)
		at org.hibernate.event.internal.DefaultLoadEventListener.onLoad(DefaultLoadEventListener.java:150)
		at org.hibernate.internal.SessionImpl.fireLoad(SessionImpl.java:1070)
		at org.hibernate.internal.SessionImpl.access$2000(SessionImpl.java:176)
		at org.hibernate.internal.SessionImpl$IdentifierLoadAccessImpl.load(SessionImpl.java:2551)
		at org.hibernate.internal.SessionImpl.get(SessionImpl.java:955)
		at org.hibernate.jpa.spi.AbstractEntityManagerImpl.find(AbstractEntityManagerImpl.java:1110)
		at org.hibernate.jpa.spi.AbstractEntityManagerImpl.find(AbstractEntityManagerImpl.java:1074)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:497)
		at org.springframework.orm.jpa.ExtendedEntityManagerCreator$ExtendedEntityManagerInvocationHandler.invoke(ExtendedEntityManagerCreator.java:344)
		at com.sun.proxy.$Proxy71.find(Unknown Source)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:497)
		at org.springframework.orm.jpa.SharedEntityManagerCreator$SharedEntityManagerInvocationHandler.invoke(SharedEntityManagerCreator.java:291)
		at com.sun.proxy.$Proxy71.find(Unknown Source)
		at org.springframework.data.jpa.repository.support.SimpleJpaRepository.findOne(SimpleJpaRepository.java:237)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:497)
		at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.executeMethodOn(RepositoryFactorySupport.java:436)
		at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:421)
		at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:393)
		at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
		at org.springframework.data.repository.core.support.RepositoryFactorySupport$DefaultMethodInvokingMethodInterceptor.invoke(RepositoryFactorySupport.java:506)
		at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
		at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
		at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
		at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
		at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
		at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:136)
		at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
		at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodIntercceptor.invoke(CrudMethodMetadataPostProcessor.java:122)
		at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
		at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
		at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
		at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
		at com.sun.proxy.$Proxy73.findOne(Unknown Source)
		at org.springframework.data.repository.CrudRepository$findOne.call(Unknown Source)
		at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
		at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:110)
		at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:122)
		at com.tliu3.demo.service.UserService.update(UserService.groovy:39)
		at com.tliu3.demo.service.UserService$$FastClassBySpringCGLIB$$2474e212.invoke(<generated>)
		at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
		at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:717)
		at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
		at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
		at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
		at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
		at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
		at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:653)
		at com.tliu3.demo.service.UserService$$EnhancerBySpringCGLIB$$a16f5425.update(<generated>)
		at com.tliu3.demo.service.UserService$update$0.call(Unknown Source)
		at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
		at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:110)
		at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:130)
		at com.tliu3.demo.controllers.UserController.update(UserController.groovy:50)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:497)
		at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
		at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
		at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
		at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:776)
		at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:705)
		at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
		at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
		at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
		at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:967)
		at org.springframework.web.servlet.FrameworkServlet.doPut(FrameworkServlet.java:880)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:651)
		at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:843)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
		at org.springframework.boot.actuate.autoconfigure.EndpointWebMvcAutoConfiguration$ApplicationContextHeaderFilter.doFilterInternal(EndpointWebMvcAutoConfiguration.java:295)
		at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
		at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:102)
		at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
		at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77)
		at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
		at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:85)
		at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
		at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:68)
		at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
		at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)
		at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:668)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1521)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1478)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.lang.Thread.run(Thread.java:745)
	Caused by: java.lang.RuntimeException: java.io.StreamCorruptedException: Unknown serialized type
		at de.ruedigermoeller.serialization.util.FSTUtil.rethrow(FSTUtil.java:119)
		at de.ruedigermoeller.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:265)
		at de.ruedigermoeller.serialization.FSTObjectInput.readArray(FSTObjectInput.java:831)
		at de.ruedigermoeller.serialization.FSTObjectInput.instantiateArray(FSTObjectInput.java:326)
		at de.ruedigermoeller.serialization.FSTObjectInput.instantiateSpecialTag(FSTObjectInput.java:288)
		at de.ruedigermoeller.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:255)
		at de.ruedigermoeller.serialization.FSTObjectInput.readObjectFields(FSTObjectInput.java:537)
		at de.ruedigermoeller.serialization.FSTObjectInput.instantiateAndReadNoSer(FSTObjectInput.java:403)
		at de.ruedigermoeller.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:262)
		at de.ruedigermoeller.serialization.FSTObjectInput.readObjectInternal(FSTObjectInput.java:230)
		at de.ruedigermoeller.serialization.FSTObjectInput.readObject(FSTObjectInput.java:210)
		at de.ruedigermoeller.serialization.FSTObjectInput.readObject(FSTObjectInput.java:165)
		... 131 common frames omitted
	Caused by: java.io.StreamCorruptedException: Unknown serialized type
		at java.time.Ser.readInternal(Ser.java:271)
		at java.time.Ser.readExternal(Ser.java:246)
		at de.ruedigermoeller.serialization.FSTObjectInput.instantiateAndReadNoSer(FSTObjectInput.java:393)
		at de.ruedigermoeller.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:262)
		... 141 common frames omitted

The "unknown serialized type" value is 66, which is unknown to the `java.time.Ser` class. Valid range is `1..14`.

Here are my entities:
`BaseEntity`:

	package com.tliu3.demo.db.model

	import java.time.LocalDateTime
	import javax.persistence.Column
	import javax.persistence.GeneratedValue
	import javax.persistence.GenerationType
	import javax.persistence.Id
	import javax.persistence.MappedSuperclass
	import javax.persistence.PrePersist
	import javax.persistence.PreUpdate
	import javax.persistence.Version

	import org.hibernate.annotations.Type

	import groovy.transform.ToString

	@MappedSuperclass
	@ToString(includeNames = true, includePackage = false, excludes = [])
	public class BaseEntity {

		@Id
		@GeneratedValue(strategy = GenerationType.AUTO)
		Long id

		@Version
		Long version

		@Type(type = "org.jadira.usertype.dateandtime.threeten.PersistentLocalDateTime")
		@Column(name = "create_date", updatable = false, nullable = false)
		LocalDateTime createDate;

		@Type(type = "org.jadira.usertype.dateandtime.threeten.PersistentLocalDateTime")
		@Column(name = "update_date", updatable = false, nullable = false)
		LocalDateTime updateDate;

		@PrePersist
		@PreUpdate
		private void updateTimestamps() {
			updateDate = LocalDateTime.now()
			if (createDate == null) {
				createDate = LocalDateTime.now()
			}
		}
	}

`User` Entity:

	package com.tliu3.demo.db.model

	import javax.persistence.Entity
	import javax.persistence.Table

	import org.hibernate.annotations.Cache
	import org.hibernate.annotations.CacheConcurrencyStrategy

	import groovy.transform.ToString

	@Entity
	@Table(name = "user")
	@ToString(includePackage = false, includeNames = true, includeSuper = true)
	@Cache(region = "common", usage = CacheConcurrencyStrategy.TRANSACTIONAL)
	public class User extends BaseEntity {
		String name

		String sex

		Long age
	}

**Comment by debop** [comment]
I used FST for JVM 1.6.
I will changing FST to JVM 1.8 supported version as soon as possible.

**Comment by debop** [comment]
Upgrade FST for JVM 1.8.
