### ISSUE TITLE
hibernate.redis.properties file configure redis.password cant work

### ISSUE THREAD

**Issue by forfuns** [debop/hibernate-redis#41]
```
......
 # redis.timeout=2000
 redis.password=password
```

error logs message : 

21:03:18.812 [Thread-11] WARN  o.h.cache.redis.jedis.JedisClient - Error in Cache Expiration Method.
redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at redis.clients.util.Pool.getResource(Pool.java:42) ~[jedis-2.5.1.jar:na]
	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:84) ~[jedis-2.5.1.jar:na]
	at org.hibernate.cache.redis.jedis.JedisClient.run(JedisClient.java:510) ~[hibernate-redis-1.6.1.jar:na]
	at org.hibernate.cache.redis.jedis.JedisClient.expire(JedisClient.java:342) ~[hibernate-redis-1.6.1.jar:na]
	at org.hibernate.cache.redis.AbstractRedisRegionFactory$1.run(AbstractRedisRegionFactory.java:177) [hibernate-redis-1.6.1.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]
Caused by: redis.clients.jedis.exceptions.JedisDataException: ERR Client sent AUTH, but no password is set
	at redis.clients.jedis.Protocol.processError(Protocol.java:113) ~[jedis-2.5.1.jar:na]
	at redis.clients.jedis.Protocol.process(Protocol.java:131) ~[jedis-2.5.1.jar:na]
	at redis.clients.jedis.Protocol.read(Protocol.java:200) ~[jedis-2.5.1.jar:na]
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:285) ~[jedis-2.5.1.jar:na]
	at redis.clients.jedis.Connection.getStatusCodeReply(Connection.java:184) ~[jedis-2.5.1.jar:na]
	at redis.clients.jedis.BinaryJedis.auth(BinaryJedis.java:2193) ~[jedis-2.5.1.jar:na]
	at redis.clients.jedis.JedisFactory.makeObject(JedisFactory.java:67) ~[jedis-2.5.1.jar:na]
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:819) ~[commons-pool2-2.0.jar:2.0]
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:429) ~[commons-pool2-2.0.jar:2.0]
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:360) ~[commons-pool2-2.0.jar:2.0]
	at redis.clients.util.Pool.getResource(Pool.java:40) ~[jedis-2.5.1.jar:na]
	... 5 common frames omitted

if I don't set reds password , can work. 
and I use redid-cli connect redid-server with password is ok !

is just some bug that skip test case ?

**Comment by forfuns** [comment]
I saw the debug code , is code cache not update , not a bug , sorry , my mistake
