### ISSUE TITLE
Does hibernate-redis work with cglib?

### ISSUE THREAD

**Issue by eweise** [debop/hibernate-redis#44]
Hi!

I'm getting a deserialize warning when trying to access a lazily instantiated reference. Do you know if this library supports CGLIB and if so Is there anything special I need to do to support lazy references?

Thank You
Eric

12:53:40:309  WARN redis.serializer.FstRedisSerializer:62 - Fail to deserialize bytes.
java.io.IOException: java.lang.RuntimeException: java.io.StreamCorruptedException: Unknown serialized type
	at de.ruedigermoeller.serialization.FSTObjectInput.readObject(FSTObjectInput.java:168)
	at org.hibernate.cache.redis.serializer.FstRedisSerializer.deserialize(FstRedisSerializer.java:60)
	at org.hibernate.cache.redis.serializer.SnappyRedisSerializer.deserialize(SnappyRedisSerializer.java:41)
	at org.hibernate.cache.redis.jedis.JedisClient.deserializeValue(JedisClient.java:502)
	at org.hibernate.cache.redis.jedis.JedisClient.get(JedisClient.java:179)
	at org.hibernate.cache.redis.regions.RedisTransactionalDataRegion.get(RedisTransactionalDataRegion.java:75)
	at org.hibernate.cache.redis.strategy.NonStrictReadWriteRedisEntityRegionAccessStrategy.get(NonStrictReadWriteRedisEntityRegionAccessStrategy.java:48)
	at org.hibernate.engine.internal.CacheHelper.fromSharedCache(CacheHelper.java:55)
	at org.hibernate.engine.internal.CacheHelper.fromSharedCache(CacheHelper.java:67)
	at org.hibernate.event.internal.DefaultLoadEventListener.loadFromSecondLevelCache(DefaultLoadEventListener.java:598)
	at org.hibernate.event.internal.DefaultLoadEventListener.doLoad(DefaultLoadEventListener.java:452)
	at org.hibernate.event.internal.DefaultLoadEventListener.load(DefaultLoadEventListener.java:213)
	at org.hibernate.event.internal.DefaultLoadEventListener.onLoad(DefaultLoadEventListener.java:146)
	at org.hibernate.internal.SessionImpl.fireLoad(SessionImpl.java:1106)
	at org.hibernate.internal.SessionImpl.immediateLoad(SessionImpl.java:1012)
	at org.hibernate.proxy.AbstractLazyInitializer.initialize(AbstractLazyInitializer.java:174)
	at org.hibernate.proxy.AbstractLazyInitializer.getImplementation(AbstractLazyInitializer.java:286)
	at org.hibernate.proxy.pojo.javassist.JavassistLazyInitializer.invoke(JavassistLazyInitializer.java:185)
	at com.compay.domain.portfolio.Asset_$$_jvst5c6_44.hashCode(Asset_$$_jvst5c6_44.java)

**Comment by johnou** [comment]
@eweise I have forked this project with bostanio, feel free to try out our 1.6.3 release which has an updated fst dependency.

**Comment by debop** [comment]
Thanks @johnou 
@eweise  will fixing 2.x

**Comment by debop** [comment]
hibernate 2.0.0 not include fst. 
Just include latest fst library in your application.
