### ISSUE TITLE
SingletonRedisRegionFactory is not loading in spring xml based config

### ISSUE THREAD

**Issue by nileshprataprao** [debop/hibernate-redis#57]
I am trying to configure this with xml based config but  it throwing error. here is my config file
`	<property name="hibernate.cache.use_second_level_cache" value="true" />
			<property name="hibernate.cache.use_query_cache" value="true" />
			<property name="hibernate.cache.region_prefix" value="hibernate" />
			<property name="hibernate.cache.query_cache_factory" value="org.hibernate.cache.redis.hibernate5.SingletonRedisRegionFactory" />
			<property name="hibernate.cache.provider_configuration_file_resource_path" value="statchat-app.properties"/> `

but it is is throwing an error for constructor  

`Caused by: org.hibernate.boot.registry.selector.spi.StrategySelectionException: Could not instantiate named strategy class [org.hibernate.cache.redis.hibernate5.SingletonRedisRegionFactory]
	at org.hibernate.boot.registry.selector.internal.StrategySelectorImpl.resolveDefaultableStrategy(StrategySelectorImpl.java:170)
	at org.hibernate.boot.registry.selector.internal.StrategySelectorImpl.resolveDefaultableStrategy(StrategySelectorImpl.java:126)
	at org.hibernate.boot.internal.SessionFactoryBuilderImpl$SessionFactoryOptionsStateStandardImpl.<init>(SessionFactoryBuilderImpl.java:649)
	at org.hibernate.boot.internal.SessionFactoryBuilderImpl.<init>(SessionFactoryBuilderImpl.java:118)
	at org.hibernate.boot.internal.MetadataImpl.getSessionFactoryBuilder(MetadataImpl.java:135)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:876)
	at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:60)
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:343)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:319)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1637)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574)
	... 46 more
Caused by: java.lang.InstantiationException: org.hibernate.cache.redis.hibernate5.SingletonRedisRegionFactory
	at java.lang.Class.newInstance(Class.java:427)
	at org.hibernate.boot.registry.selector.internal.StrategySelectorImpl.resolveDefaultableStrategy(StrategySelectorImpl.java:166)
	... 56 more
Caused by: java.lang.NoSuchMethodException: org.hibernate.cache.redis.hibernate5.SingletonRedisRegionFactory.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.newInstance(Class.java:412)
	... 57 more`

**Comment by sandippatil** [comment]
What is the solution for this? I am facing same issue.
